GradesApp/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GradesApp.Data;
using GradesApp.Data.Entities;
using GradesApp.Services.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using GradesApp.DTOs;
using NuGet.DependencyResolver;
using AutoMapper;
using Humanizer;


namespace GradesApp.Controllers
{
    public class GradesController : Controller
    {
        private readonly IGradeService _gradeService;
        private readonly ITeacherService _teacherService;
        private readonly ISubjectService _subjectService;
        private readonly IStudentService _studentService;
        private readonly IMapper _mapper;
        private readonly UserManager<IdentityUser> _userManager;


        public GradesController(IMapper mapper, IStudentService studentService, IGradeService gradeService, ITeacherService teacherService, UserManager<IdentityUser> userManager, ISubjectService subjectService)
        {
            _mapper = mapper;
            _studentService = studentService;
            _gradeService = gradeService;
            _teacherService = teacherService;
            _userManager = userManager;
            _subjectService = subjectService;
        }

        // GET: Grades
        public async Task<IActionResult> Index()
        {
            return View(await _gradeService.GetAllAsync());
        }

        // GET: Grades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _gradeService.GetByIdAsync(id.Value);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }
        [Authorize(Roles = "Teacher")]
        // GET: Grades/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            var teacher = _teacherService.GetByAccountId(user.Id).First();
            var students = await _studentService.GetAllAsync();
            var createDTO = new CreateGradeDTO 
            {
                Students = students.Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.FirstName + " " + s.LastName,
                }).ToList(),
                TeacherId = teacher.Id,
                SubjectId = teacher.Subject.Id
            };
            return View(createDTO);
        }

        // POST: Grades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create(CreateGradeDTO gradeDTO)
        {
            if (!ModelState.IsValid)
            {
                gradeDTO.Students = (await _studentService.GetAllAsync())
                    .Select(s => new SelectListItem { Value = s.Id.ToString(), 
                        Text = s.FirstName + " " + s.LastName })
                    .ToList();

                return View(gradeDTO);
            }

            try
            {
                await _gradeService.CreateAsync(gradeDTO);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
                ModelState.AddModelError("", "An unexpected error occurred.");
                return View(gradeDTO);
            }

        }

        // GET: Grades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            var teacher = _teacherService.GetByAccountId(user.Id).FirstOrDefault();
            var grade = await _gradeService.GetByIdAsync(id.Value);
            
            if (grade == null)
            {
                return NotFound();
            }
            if (teacher == null || grade.TeacherId != teacher.Id)
            {
                return Forbid(); 
            }
            var dto = _mapper.Map<CreateGradeDTO>(grade);
            var students = await _studentService.GetAllAsync();
            dto.Students = students.Select(s => new SelectListItem
            {
                Value = s.Id.ToString(),
                Text = $"{s.FirstName} {s.LastName}"
            }).ToList();
            return View(dto);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateGradeDTO gradeDTO)
        {
            if (id != gradeDTO.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                gradeDTO.Students = (await _studentService.GetAllAsync())
                    .Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.FirstName + " " + s.LastName
                    })
                    .ToList();

                return View(gradeDTO);
            }

            try
            {
                await _gradeService.UpdateAsync(gradeDTO);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
                ModelState.AddModelError("", "An unexpected error occurred.");
                return View(gradeDTO);
            }
        }

        // GET: Grades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            var teacher = _teacherService.GetByAccountId(user.Id).FirstOrDefault();
            var grade = await _gradeService.GetByIdAsync(id.Value);
            if (grade == null)
            {
                return NotFound();
            }
            if (teacher == null || grade.TeacherId != teacher.Id)
            {
                return Forbid();
            }
            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _gradeService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool GradeExists(int id)
        {
            return _gradeService.GetByIdAsync(id) != null;
        }
    }
}

GradesApp/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GradesApp.Data;
using GradesApp.Data.Entities;
using GradesApp.Services.Abstractions;
using GradesApp.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace GradesApp.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly UserManager<IdentityUser> _userManager;
        public StudentsController(IStudentService studentService, UserManager<IdentityUser> userManager)
        {
            _studentService = studentService;
            _userManager = userManager;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            return View(await _studentService.GetAllAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _studentService.GetByIdAsync(id.Value);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(StudentDTO studentDto)
        {
            if (ModelState.IsValid)
            {
                await _studentService.CreateAsync(studentDto);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }
            return View(studentDto);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _studentService.GetByIdAsync(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, StudentDTO studentDto)
        {
            if (id != studentDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _studentService.UpdateAsync(studentDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await StudentExistsAsync(studentDto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(studentDto);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _studentService.GetByIdAsync(id.Value);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _studentService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> StudentExistsAsync(int id)
        {
            return await _studentService.GetByIdAsync(id) != null;
        }
    }
}

GradesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GradesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GradesApp.styles.css" asp-append-version="true" />
</head>
<body style="background-color: antiquewhite">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GradesApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grades" asp-action="Index">Grades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted align-content-center">
        <div class="container">
            2025  GradesApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>